---
title: "Lab2 R Codes"
author: "Weichang Yu"
date: "26/06/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Set Home Directory
```{r}
# setwd("/home/yourname/NYCTaxiData")
```

Load data
```{r}
mydata = read.csv("sample.csv")
dim(mydata)
```

Install t-map package (Library for thematic maps) and other required R packages
```{r}
#install.packages("dplyr")
#install.packages("sf")
#install.packages("curl")
#Restart your R Session
#install.packages("tmap")
```

Install ggmap
```{r}
#install.packages("ggmap")

#OR (choose whichever works on your computer)

#install.packages("devtools")
#devtools::install_github("dkahle/ggmap")
```


Load libraries
```{r, message=FALSE, warning=FALSE}
library(dplyr)
library(sf)
library(curl)
library(ggmap)
library(tmap)
library(tmaptools)
```


Download and view map
```{r, message=FALSE, warning=FALSE}
map<-get_stamenmap(rbind(as.numeric(paste(geocode_OSM("Manhattan")$bbox))), zoom = 11)
ggmap(map)
```

Plot pickup locations
```{r, message=FALSE, warning=FALSE}
ggmap(map) + geom_point(aes(x = pickup_longitude, y = pickup_latitude),colour="white", size = 0.01, data = mydata, alpha = .5)
```

Square binning
```{r, message=FALSE, warning=FALSE}
plotmap <- ggmap(map) + geom_bin2d(bins=100, data=mydata, aes(x =
pickup_longitude, y = pickup_latitude))
plotmap
```

Install HexBin
```{r, message=FALSE, warning=FALSE}
#install.packages("hexbin")
```

Plot HexBin
```{r, message=FALSE, warning=FALSE}
plotmapHB <- ggmap(map) + coord_cartesian() + geom_hex(bins=100, data=mydata,
aes(x = pickup_longitude, y = pickup_latitude))
plotmapHB
```

Load Data into SparklyR
```{r, message=FALSE, warning=FALSE}
library(sparklyr)
library(dplyr)
sc <- spark_connect(master = "local")
nyc_taxi <- spark_read_csv(sc, name = "taxi_data", path ="sample.csv", header = TRUE, delimiter = ",")
```

Manual square binning by rounding
```{r, message=FALSE, warning=FALSE}
nyc_taxi <- nyc_taxi %>%
mutate(pickup_latitude = round(pickup_latitude,3))%>%
mutate(pickup_longitude = round(pickup_longitude,3))%>%
sdf_register("nyc_taxi")
```

Saving data
```{r, message=FALSE, warning=FALSE}
spark_write_csv(nyc_taxi,"rounded",header=TRUE,delimiter=",", mode="overwrite")
```

Calling data summary and saving
```{r, message=FALSE, warning=FALSE}
nyc_taxi_summary <- nyc_taxi %>%
group_by(pickup_latitude, pickup_longitude) %>%
summarise(n=n()) %>%
sdf_register("nyc_taxi_summary")
#save summary
spark_write_csv(nyc_taxi_summary,"summary",header=TRUE,delimiter=",", mode="overwrite")
```

Saving summary
```{r, message=FALSE, warning=FALSE}
plotmap <- ggmap(map) + geom_point(aes(x = pickup_longitude, y = pickup_latitude, colour=n, fill=n), data = nyc_taxi_summary, shape=22, size=0.25)
ggsave("plot.png")
```
